In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Пример

Найти *вторую* производную таблично заданной функции с максимально возможной точностью

In [3]:
fi = np.array([5, 7, 8, 10, 11], dtype=float)
xi = np.array([1, 2, 3, 4, 5], dtype=float)

Метод неопределенных коэффициентов

In [4]:
n = len(xi)
n

5

In [7]:
x_0 = 3.0
# ищем вторую производную в этой точке

b -  столбец **вторых** производных базисных функций $ 1, x, x^{2}, x^{3}, x^{4} $

в точке $x_0$ = 3.0

In [8]:
b = np.array([0, 0, 2, 6*x_0, 12*(x_0**2)], dtype=float)
b

array([  0.,   0.,   2.,  18., 108.])

In [9]:
A = np.ones((n, n), dtype=float)
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
for i in range(n):
    for j in range(n):
        A[i][j] *= (xi[j]**i)
A

array([[  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5.],
       [  1.,   4.,   9.,  16.,  25.],
       [  1.,   8.,  27.,  64., 125.],
       [  1.,  16.,  81., 256., 625.]])

In [11]:
# решаем СЛАУ Ab = c
c = np.linalg.solve(A, b)
c

array([-0.08333333,  1.33333333, -2.5       ,  1.33333333, -0.08333333])

**Ответ:**

In [12]:
ans = 0
for j in range(n):
    ans += fi[j]*c[j]
ans

1.3333333333333228

## Задача

Для сеточной функции вычислить производную в точке 1950 с максимально возможной точностью

Решим методом неопределенных коэффициентов

In [13]:
# сетка и значения функции на ней
xi = np.array([1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000], dtype=float)
fi = np.array([92228496, 106021537, 123202624, 132164569,
          151325798, 179323175, 203211926, 226545805,
          248709873, 281421906], dtype=float)

In [14]:
x_0 = 1950.0

In [15]:
n = len(xi)
n

10

b -  столбец производных базисных функций $ 1, x, x^{2}, x^{3}, ..., x^{n-1} $, где n = 10

вычисленных в точке xo = 1950

In [16]:
b = []
for i in range(n):
    elem = i * (x_0**(i-1))
    b.append(elem)
b = np.array(b, dtype=float)
b

array([0.00000000e+00, 1.00000000e+00, 3.90000000e+03, 1.14075000e+07,
       2.96595000e+10, 7.22950312e+13, 1.69170373e+17, 3.84862599e+20,
       8.57693792e+23, 1.88156576e+27])

In [17]:
A = np.ones((n, n), dtype=float)

A - матрица нашей системы 

In [18]:
for i in range(n):
    for j in range(n):
        A[i][j] *= (xi[j]**i)
A

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       [1.91000000e+03, 1.92000000e+03, 1.93000000e+03, 1.94000000e+03,
        1.95000000e+03, 1.96000000e+03, 1.97000000e+03, 1.98000000e+03,
        1.99000000e+03, 2.00000000e+03],
       [3.64810000e+06, 3.68640000e+06, 3.72490000e+06, 3.76360000e+06,
        3.80250000e+06, 3.84160000e+06, 3.88090000e+06, 3.92040000e+06,
        3.96010000e+06, 4.00000000e+06],
       [6.96787100e+09, 7.07788800e+09, 7.18905700e+09, 7.30138400e+09,
        7.41487500e+09, 7.52953600e+09, 7.64537300e+09, 7.76239200e+09,
        7.88059900e+09, 8.00000000e+09],
       [1.33086336e+13, 1.35895450e+13, 1.38748800e+13, 1.41646850e+13,
        1.44590062e+13, 1.47578906e+13, 1.50613848e+13, 1.53695362e+13,
        1.56823920e+13, 1.60000000e+13],
       [2.54194902e+16, 2.60919263e+16, 2.67785184e+16, 2.74794888e+16,
   

In [19]:
# решаем СЛАУ Ac = b
c = np.linalg.solve(A, b)
c

array([-0.01205423,  0.08956539, -0.28073202,  0.45316553, -0.54878398,
        0.37964611, -0.05487479, -0.05140185,  0.03085938, -0.00538955])

**Ответ:**

In [20]:
ans = 0
for j in range(n):
    ans += fi[j]*c[j]
ans

2086005.638530578